### ISSUE TITLE
can't find the file path/rk3308_defconfig please fix this script

### ISSUE THREAD

**Issue by kleysoncastro** [flatmax/buildroot.rockchip#16]
I followed the steps to build, however I have the same result for the rk3308 chip and the others.

```sh
➜  $ tree -L 1
├── buildroot
└── buildroot.rockchip.ext
```
rock pi S tested with version : `git checkout 2022.02.1` ok

`exec command` 
```sh
➜  $ source buildroot.rockchip.ext/setup.rk3308.sh buildroot          
can't find the file /home/castro/kernel-rock/configs/rk3308_defconfig
please fix this script
```

as defconfig already exists in buildroot, it worked. I already apologize if I'm doing something wrong.

**Comment by flatmax** [comment]
Thanks for writing a very clear issue.

Can you please try using the full path to the ext and buildroot directories ?
source /full-path/buildroot.rockchip.ext/setup.rk3308.sh /full-path/buildroot

Does that help ?

**Comment by flatmax** [comment]
Please add source in front of the command

**Comment by kleysoncastro** [comment]
It wasn't clear to me that I had to go into the `buildroot.rockchip.ext` directory and run the source inside. but I managed, I entered ` buildroot.rockchip.ext` and it worked. 
obrigado

**Comment by flatmax** [comment]
Beleza !
