### ISSUE TITLE
a repository not exist, and file on sources.buildroot.net not exist

### ISSUE THREAD

**Issue by 1190201119** [flatmax/buildroot.rockchip#2]
I try to build on radxa rock 3a, but failed.
I followed the instructions, in the step "Now build buildroot as per usual", can't finish make.

problem 1:
remote: Repository not found.
fatal: 仓库 'https://github.com/rockchip-linux/device-custom.git/' 未找到
...
This is the second time in a row; bailing out

problem 2:
--2022-02-27 19:54:59--  http://sources.buildroot.net/rkdevice-0fe366cf14a6d5d552a5bddbc7b8ff58260ae6e6-br1.tar.gz
正在解析主机 sources.buildroot.net (sources.buildroot.net)... 104.26.1.37, 104.26.0.37, 172.67.72.56, ...
正在连接 sources.buildroot.net (sources.buildroot.net)|104.26.1.37|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 404 Not Found

It seems that that repository and that file don't exist. How can I fix this problem?

**Comment by StephenInVamrs** [comment]
> problem 1:
> remote: Repository not found.
> fatal: 仓库 'https://github.com/rockchip-linux/device-custom.git/' 未找到
> ...
> This is the second time in a row; bailing out

How about using this repository, https://github.com/radxa/device-custom.git?

**Comment by flatmax** [comment]
ok-  I updated the readme. You should checkout the buildroot repo commit as mentioned :
```
# rock pi 3a tested with version : git checkout 73248c03fd04eddad78fea5096cd98b2a2d43e81
```

If that doesn't fix your problem, plese write all of the commands from begginning to end which you used to build.

**Comment by daydream-noquitter** [comment]
> ok- I updated the readme. You should checkout the buildroot repo commit as mentioned :
> 
> ```
> # rock pi 3a tested with version : git checkout 73248c03fd04eddad78fea5096cd98b2a2d43e81
> ```
> 
> If that doesn't fix your problem, plese write all of the commands from begginning to end which you used to build.

Here are my commands
mkdir rock-3a
cd rock-3a/
 git clone git://git.busybox.net/buildroot buildroot
cd buildroot
git checkout 73248c03fd04eddad78fea5096cd98b2a2d43e81
cd ..
sudo apt-get install -y build-essential gcc g++ autoconf automake libtool bison flex gettext
sudo apt-get install -y patch texinfo wget git gawk curl lzma bc quilt
git clone https://github.com/flatmax/buildroot.rockchip.git buildroot.rockchip.ext
source buildroot.rockchip.ext/setup.rock3a.sh buildroot
make rkbin
make 
when run "make "  
wget --passive-ftp -nd -t 3 -O '/home/hit/rock-3a/buildroot/output/build/.uboot-fd3d0a5310494dcbba510406e1e2d66806c1b901-br1.tar.gz.Yba7f8/output' 'http://sources.buildroot.net/uboot-fd3d0a5310494dcbba510406e1e2d66806c1b901-br1.tar.gz'
--2022-02-28 21:01:19--  http://sources.buildroot.net/uboot-fd3d0a5310494dcbba510406e1e2d66806c1b901-br1.tar.gz
404 not found 


GIT_DIR=/home/hit/rock-3a/buildroot.dl/uboot/git/.git git remote add origin 'https://github.com/radxa/u-boot.git'
GIT_DIR=/home/hit/rock-3a/buildroot.dl/uboot/git/.git git remote set-url origin 'https://github.com/radxa/u-boot.git'
Fetching all references
GIT_DIR=/home/hit/rock-3a/buildroot.dl/uboot/git/.git git fetch origin
error: RPC failed.curl 56 GnuTLS recv error (-54): 
How to fix it ? Thanks for  your help!

**Comment by flatmax** [comment]
How long does make rkbin take to run ?
What is in your buildroot/output/build directory ?

If you look in the config file this is how uboot is defined :
```
BR2_TARGET_UBOOT_CUSTOM_REPO_URL="https://github.com/radxa/u-boot.git"
```

Buildroot should be fetching uboot from that URL, not sources.buildroot.net.

Have you setup the downloads directory, perhaps that is the problem ?
cd buildroot; mkdir ../buildroot.dl

**Comment by flatmax** [comment]
> > problem 1:
> > remote: Repository not found.
> > fatal: 仓库 'https://github.com/rockchip-linux/device-custom.git/' 未找到
> > ...
> > This is the second time in a row; bailing out
> 
> How about using this repository, https://github.com/radxa/device-custom.git?

Can you please start a new thread somewhere else for this device-custom.git ?
This issue is related to the buildroot.rockchip repo, not the device-custom repo.

**Comment by flatmax** [comment]
Closing this issue due to cross polination with a "device-custom" repo discussion.
